import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });
let activepeoples = {};
const interval = setInterval(() => {
  fetch(
    "https://avenuecorporation.in/api/tracker?action=" +
      btoa("REQUEST_ACTIVE_USERS")
  )
    .then((res) => res.text())
    .then((res) =>
      !res.includes("<")
        ? JSON.parse(res)
        : {
            avenuepacks: 0,
            avenuecorporation: 0,
          }
    )
    .then((res) => {
      if (typeof res === "object" && !res.status) {
        document.getElementById("avenuepacks_count").innerHTML =
          res["avenuepacks"];
          document.getElementById("avenuecorporation_count").innerHTML =
          res["avenuecorporation"];
      }
    })
    .catch((err) => {
      console.log(err);
    });
}, 10000);

export default function Home() {
  const [activeUsers, setActiveUsers] = useState(activepeoples);
  useEffect(() => {
    setActiveUsers(activepeoples);
  }, [activepeoples]);
  return (
    <>
      <Head>
        <title>Avenue Corporation</title>
        <meta name="description" content="Generated by Avenue Corporation" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h4>Active Users</h4>
          <div className="active-users">
            <div className="container">
              <span className="zero" id="avenuepacks_count"></span>
              <p>Avenue Packs</p>
            </div>
            <div className="container">
              <span className="zero" id="avenuecorporation_count"></span>
              <p>Avenue Corporation</p>
            </div>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
